### ISSUE TITLE
Sync username from Keycloak

### ISSUE THREAD

**Issue by Cartasiane** [cryptpad/sso#1]
When I create a new account with keycloak the account user is something like u6a2vosi8rc95t/ndpmw1bpy84qxoabl

is it what `not supported: Store extra information from users coming from SSO `mean or did I configure something wrongly?

**Comment by yflory** [comment]
Hello,
This can probably be fixed by [this merged PR](https://github.com/cryptpad/sso/pull/5/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R81) by configuring `username_scope` and/or `username_claim` to match the ones used in your Keycloak config. By default, the username scope is `profile` and the claim is `name`.
